language: python

python:
  - '3.6'

addons:
  apt:
    packages:
    - xclip

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # give xvfb some time to start

script:
  - pipenv run pytest
